export const MOCK_CHATS = [
  {
    projectId: 'p1',
    messages: [
      { id: '1', role: 'user', content: 'Create a yield rebalancer that moves USDT between Venus and Radiant on BSC when the APY difference is > 1%.', timestamp: '2024-03-20T10:00:00Z' },
      { id: '2', role: 'assistant', content: "I've analyzed your yield optimization request. Moving assets between Venus and Radiant involves monitoring supply APY and checking if the gas cost of the bridge/rebalance makes sense. I can build this for you. ", timestamp: '2024-03-20T10:00:05Z' },
      { id: '3', role: 'assistant', content: "To proceed, I need the precise minimum amount for the swap and your preference on bridging risk between layers if you choose to expand this to Polygon.", timestamp: '2024-03-20T10:00:10Z' }
    ]
  },
  {
    projectId: 'p2',
    messages: [
      { id: '1', role: 'user', content: 'Buy 0.1 ETH worth of PEPE every time the price drops 5% in 1 hour.', timestamp: '2024-03-20T11:00:00Z' },
      { id: '2', role: 'assistant', content: "Got it. This is a classic DCA (Dollar Cost Averaging) strategy triggered by price volatility. I'll set up a Price Feed monitor and an Uniswap V3 swap action.", timestamp: '2024-03-20T11:00:05Z' }
    ]
  }
];

export const MOCK_CODE_PYTHON = `
import requests
import json
from decimal import Decimal

def execute_rebalance(context):
    """
    Tactical Yield Rebalancer Logic
    Generated by Onchain AI Agent HUB
    """
    print(f"Executing rebalance for node: {context['agent_address']}")
    
    # 1. Fetch APY from Oracles
    venus_apy = context['oracle'].get_apy('VENUS_USDT')
    radiant_apy = context['oracle'].get_apy('RADIANT_USDT')
    
    threshold = context['params'].get('threshold', 1.0)
    
    if (radiant_apy - venus_apy) > threshold:
        print(f"Opportunity detected: {radiant_apy}% vs {venus_apy}%")
        
        # 2. Check Gas Efficiency
        gas_est = context['tx'].estimate_gas_units()
        if gas_est > context['params'].get('max_gas', 15.0):
            print("Aborting: Gas cost outweighs yield gain.")
            return False
            
        # 3. Trigger Withdrawal from Venus
        context['agent'].withdraw('VENUS', 'USDT', context['agent'].get_balance('VENUS', 'USDT'))
        
        # 4. Trigger Supply to Radiant
        context['agent'].supply('RADIANT', 'USDT', context['agent'].get_balance('USDT'))
        
        return True
    
    return False
`;
